import type { NextPage } from 'next'
import Head from 'next/head'
import { Header } from '../src/components/Header'
import { Stories } from '../src/components/Stories'
import { MiniProfile } from '../src/components/MiniProfile'
import { Feed } from '../src/components/Feed'
import { Modal } from '../src/components/Modal'
import { useSession } from 'next-auth/react'

const Home: NextPage = () => {
	const { data: session, status } = useSession()
	return (
		<div>
			<Head>
				<title>Instagram | {session?.user.name || status + '...'}</title>
				<meta name='description' content='Generated by create next app' />
			</Head>
			<main>
				<Header />
				<>
					<div className='grid relative grid-cols-2 grid-rows-1 lg:grid-cols-3 lg:grid-rows-2 items-center'>
						<Stories />
						<MiniProfile />
						<Feed />
					</div>
					<Modal />
				</>
			</main>
		</div>
	)
}

export default Home
