import type { NextPage } from 'next'
import Head from 'next/head'
import { Header } from '../src/components/Header'
import { Stories } from '../src/components/Stories'

const Home: NextPage = () => {
	return (
		<div>
			<Head>
				<title>Instagram | MSpilari</title>
				<meta name='description' content='Generated by create next app' />
			</Head>
			<main>
				<Header />
				<div className='grid grid-cols-2 lg:grid-cols-3 items-center'>
					<Stories />
					{/* <Feed /> */}
					{/* Mini Profile */}
					{/* Sugestões */}
				</div>
			</main>
		</div>
	)
}

export default Home
